include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/generated
    - lib/generated/locale_keys.g.dart
    - lib/src/di/injectable.config.dart

  errors:
    missing_required_param: error

linter:
  rules:
    exclude:
      - sort_pub_dependencies

