name: flutter_base_project
description: Scaffold project with all basic setup.

version: 1.0.0+2

publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  easy_localization: ^2.3.3

  device_info: ^1.0.0

  package_info: ^0.4.3+4

  url_launcher: ^5.7.10

  #Firebase
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_analytics: ^7.0.1
  firebase_remote_config: ^0.6.0

  performance_interceptor:
    git:
      url: https://github.com/solutelabs/firebase_performance_interceptor.git

  connectivity: ^2.0.2
  shared_preferences: ^0.5.12+4
  permission_handler: ^5.1.0+2
  cached_network_image: ^2.5.1
  path_provider: ^1.6.28
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    # Localized strings
    - lib/assets/strings/
