name: flutter_base_project
description: Scaffold project with all basic setup.

version: 1.0.0+2

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  easy_localization: ^3.0.0

  device_info: ^2.0.2

  package_info: ^2.0.2

  url_launcher: ^6.0.6

  #Firebase
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6
  firebase_analytics: ^8.1.2
  firebase_remote_config: ^0.10.0+2

  performance_interceptor:
    git:
      url: https://github.com/kalyanig-solutelabs/firebase_performance_interceptor.git

  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
  permission_handler: ^8.1.1
  cached_network_image: ^3.0.0
  path_provider: ^2.0.2
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    # Localized strings
    - lib/assets/strings/
